[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sceleto"
authors = [{name = "scmgl", email = "scmglkaist@gmail.com"}]
dynamic = ["version", "description"]
